name: Check NIST workflow

on:
  schedule:
    - cron: '0 0 * * 0'  #runs on every Sunday midnight
  workflow_dispatch:
  
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}


jobs:
  build:

    defaults:
       run:
         shell: bash -l {0}
  
    runs-on: ubuntu-latest
    
    steps:
     # - uses: act10ns/slack@v2.0.0
      #  with:
       #   status: starting
        #  message: Starting NIST ionization energies
        #if: always()

      - name: Checkout github repo
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install package
        run: pip install git+https://github.com/tardis-sn/carsus

      - name: Run Python script
        id: run_ionization_script
        run: | 
          python ionization.py
          
      - name: Compare changes
        id: compare
        continue-on-error: true
        run: |
          git add .
          git diff --quiet --exit-code --cached

      - name: Commit files to git
        id: commit_changes
        if: ${{ steps.compare.outcome == 'failure' }}
        run: |
          git commit -m "Ionization energies added"

      - name: Push changes
        if: ${{ steps.compare.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
   #   - name: Report status 
   #     uses: act10ns/slack@v2.0.0
   #     with:
   #       status: ${{ job.status }}
   #       steps: ${{ toJson(steps) }}
   #     if: always()
          
